### ISSUE TITLE
Very slow opening PDF files for first time in EOS 6 Beta

### ISSUE THREAD

**Issue by Condor157** [elementary/evince#5] opened 2021-05-28 08:38 UTC
Very slow opening PDF files for first time in EOS 6 Beta.   
I have OES 6 Beta installed, and when I open any PDF file fi thr first time, it takes a long time. In comparison i OES5 I don't see this problem.
   
![Снимок экрана от 2021-05-28 11-42-26](https://user-images.githubusercontent.com/84856861/119956512-d6db3300-bfa9-11eb-9b6b-11f30de37eda.png)
![Снимок экрана от 2021-05-28 11-39-59](https://user-images.githubusercontent.com/84856861/119956151-751ac900-bfa9-11eb-910a-bf5f5afbab58.png)

**Comment by ryonakano** [comment] 2023-03-25 07:24
We're providing Flatpak version of Evince since elementary OS 6.x, while we'd provided native deb package until 0.5, so that might caused this issue. It's destiny for Flatpak apps to launch because they run in sandboxed environments, and that time may differ depending on your system performance.

Closing as out of scope since this is not caused by our customization (which just adds our own icons)

**Closed by ryonakano** 2023-03-25 07:24 UTC
