### ISSUE TITLE
(upstream?) Evince only partially respect dark theme

### ISSUE THREAD

**Issue by teamcons** [elementary/evince#89] opened 2024-12-19 11:03 UTC
### What Happened?

Some dialogs do not follow dark theme
Im not sure whether an issue with Evince, or Evince calls another component who takes care of the dialog

![Bildschirmfoto von 2024-12-19 11 53 44](https://github.com/user-attachments/assets/47dc6e13-88b4-42aa-af3f-9a2006f871d6)

### Steps to Reproduce

use dark theme
open a document in evince
hit print

### Expected Behavior

all dialogs follow systeme theme

### OS Version

8.x (Circe)

### Session Type

Secure Session (Wayland)

### Software Version

Latest release (I have run all updates)

**Comment by ryonakano** [comment] 2024-12-19 11:54
I suppose this might be because we don't implement the print portal in our portals repository and the one provided by [xdg-desktop-portal-gtk](https://github.com/flatpak/xdg-desktop-portal-gtk/blob/main/src/print.c) is shown instead?

**Comment by ryonakano** [comment] 2024-12-19 11:55
Ah maybe my guess would be correct: https://github.com/elementary/portals/issues/5

**Comment by ryonakano** [comment] 2024-12-19 22:15
Closing as a duplicate of the above issue.

**Closed by ryonakano** 2024-12-19 22:15 UTC
