### ISSUE TITLE
Incorrect icon in AppCenter

### ISSUE THREAD

**Issue by kdwk** [elementary/evince#11] opened 2021-07-20 03:28 UTC
## What Happened

In AppCenter, the Evince icon is still the upstream Gnome one, not the redesigned elementary OS one. 

## Expected Behavior

The Evince icon in AppCenter follows the one shown in the dock and the Applications menu

**Comment by danrabbit** [comment] 2021-07-27 16:49
Hey thanks for your report! I'm going to mark this is a duplicate of #8 since moving the icon to this repo would solve this problem

**Closed by danrabbit** 2021-07-27 16:49 UTC
